#pragma config(Sensor, in1,    Gyroscope,      sensorGyro)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           BillandBob,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           FredandJoseph, tmotorNone, openLoop)
#pragma config(Motor,  port4,           HasewandSchmeckle, tmotorNone, openLoop)
#pragma config(Motor,  port5,           Rouf,          tmotorNone, openLoop)
#pragma config(Motor,  port6,           Francis,       tmotorNone, openLoop)
#pragma config(Motor,  port7,           Ivan,          tmotorNone, openLoop)
#pragma config(Motor,  port8,           Raaj,          tmotorNone, openLoop)
#pragma config(Motor,  port9,           Austin,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//BillandBob and FredandJoseph and Francis and Rouf are the drive motors, the back ones (the ones with 2 names) are on splitters
//HasewandSchmeckle is the lift, Ivan is the claw
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
void pre_auton()
{
  bStopTasksBetweenModes = true;
  SensorType[Gyroscope] = sensorNone;
  wait1Msec(1000);
  SensorType[Gyroscope] = sensorGyro;
  wait1Msec(2000);
  SensorScale[Gyroscope] = 150;
}
void turnRight (int degreeInTens)
/*
Allows for the degree # when you call the function
to look like an actual degree amount, as opposed to
a 4 digit number
*/
{
	int degreeInOnes = (degreeInTens * 8.3333333);
	while(abs(SensorValue[Gyroscope]) < degreeInOnes)
	/*
	while loop allows for the gyroscope to turn a specific amount,
	as specified when the function is called
	*/
	{
		motor[BillandBob] = 60;
		motor[FredandJoseph] = -60;
		motor[Francis] = 60;
		motor[Rouf] = -60;
		motor[Raaj] = 60;
		motor[Austin] = -60;
	}
	motor[BillandBob] = 0;
	motor[FredandJoseph] = 0;
	motor[Francis] = 0;
	motor[Rouf] = 0;
	motor[Raaj] = 0;
	motor[Austin] = 0;
}
void turnLeft (int degreeInTens)
/*
Allows for the degree # when you call the function
to look like an actual degree amount, as opposed to
a 4 digit number
*/
{
	int degreeInOnes = (degreeInTens * 8.333333);
	while(abs(SensorValue[Gyroscope]) < degreeInOnes)
	/*
	while loop allows for the gyroscope to turn a specific amount,
	as specified when the function is called
	*/
	{
		motor[BillandBob] = -60;
		motor[FredandJoseph] = 60;
		motor[Francis] = -60;
		motor[Rouf] = 60;
		motor[Raaj] = -60;
		motor[Austin] = 60;
	}
	motor[BillandBob] = 0;
	motor[FredandJoseph] = 0;
	motor[Francis] = 0;
	motor[Rouf] = 0;
	motor[Raaj] = 0;
	motor[Austin] = 0;
}
void driveSquare (int distance, int power)
/* this sets it so that when the function is called
there is a set of parentheses with the #of squares
that will be traveled and the speed in which they
will be traversed*/
{
	SensorValue [LeftEncoder] = 0;
	int goalDistance = (1001 * distance);
	/*sets the distance traveled to our constant, which is 28,
	times the amount of squares needed, which one is 25, then
	multiplies the entire thing by the amount of squares needed,
	*/
  while(SensorValue[LeftEncoder] < goalDistance)
  {
  	motor[BillandBob] = power;
  	motor[FredandJoseph] = power;
  	motor[Francis] = power;
  	motor[Rouf] = power;
  	motor[Raaj] = power;
		motor[Austin] = power;
  }
  motor[BillandBob] = 0;
  motor[FredandJoseph] = 0;
  motor[Francis] = 0;
  motor[Rouf] = 0;
  motor[Raaj] = 0;
	motor[Austin] = 0;
  /*
  While loop allows for you to only move specified amount in the
  "coordinates" given when you call the function
  */
}
void drivesquareReverse (int distance, int power)
/* this sets it so that when the function is called
there is a set of parentheses with the #of squares
that will be traveled and the speed in which they
will be traversed*/
{
	SensorValue [LeftEncoder] = 0;
	int goalDistance = (-1001 * distance);
	/*sets the distance traveled to our constant, which is 28,
	times the amount of squares needed, which one is 25, then
	multiplies the entire thing by the amount of squares needed,
	*/
  while(SensorValue[LeftEncoder] > goalDistance)
  {
  	motor[BillandBob] = power;
  	motor[FredandJoseph] = power;
  	motor[Francis] = power;
  	motor[Rouf] = power;
  	motor[Raaj] = power;
		motor[Austin] = power;
  }
  motor[BillandBob] = 0;
  motor[FredandJoseph] = 0;
  motor[Francis] = 0;
  motor[Rouf] = 0;
  motor[Raaj] = 0;
		motor[Austin] = 0;
  /*
  While loop allows for you to only move specified amount in the
  "coordinates" given when you call the function
  */
}
void shoot(int shootTime)
/*
This is a funtion to shoot our ball launcher
*/
{
	motor[port1] = 60;
	motor[port10] = 60;
	wait1Msec(shootTime);
}

task autonomous()
{
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;
	turnLeft(90);
	//drives 2 squares a MAXIMUM EFFORT
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;
	driveSquare(1,127);
	//drives backwards 2 squares at MAXIMUM EFFORT
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;
	SensorValue[Gyroscope] = 0;
	turnRight(90);
	//turns 90 degrees counterclockwise
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;
	SensorValue[Gyroscope] = 0;
	driveSquare(3,127);
}
task usercontrol()
{
	 while (true)
  {
			{
				//Movement System
				motor[BillandBob] = vexRT[Ch3];
				motor[FredandJoseph] = vexRT[Ch2];
				motor[Francis] = vexRT[Ch2];
				motor[Rouf] = vexRT[Ch3];
				motor[Raaj] = vexRT[Ch2];
				motor[Austin] = vexRT[Ch3];
					//Lift System
				if(vexRT[Btn6U] == 1)
				{
					motor[HasewandSchmeckle] = 127;
				}
					else if(vexRT[Btn6D] == 1)
				{
					motor[HasewandSchmeckle] = -127;
				}
					else
				{
						motor[HasewandSchmeckle] = 0;
				}

						//Launcher System
						if(vexRT[Btn5U] == 1)
						{
							motor[Rouf] = 127;
							motor[Ivan] = 127;
						}
						else if(vexRT[Btn5D] == 1)
						{
							motor[Rouf] = -127;
							motor[Ivan] = -127;

						}
						else
						{
							motor[Rouf] = 0;
							motor[Ivan] = 0;
								//Claw System
							if(vexRT[Btn8L]==1)
							{
								motor[Ivan] = -36;
							}
							else if(vexRT[Btn8R]==1)
							{
								motor[Ivan] = 36;
							}
							else
							{
								motor[Ivan] = 0;
							}
				}
			}
		}
	}
